INSERT INTO Holiday (title, teaser, description, imageUrl, typeId, durationInDays, minCount, maxCount, soldOut, onSale)

VALUES ('Norway', 'Raw Nature in the North',
        'Norway, a Nordic country known for its stunning fjords, vibrant cultural heritage, and high standard of living, is characterized by a harmonious blend of natural beauty and progressive societal values.',
        '/assets/norway.jpg', 1, 14, 8, 24, false, false),
       ('India', 'Diverse landscapes, rich culture, vibrant traditions enchant visitors.',
        'From the iconic Taj Mahal in Agra to the bustling streets of Delhi and the serene backwaters of Kerala, the country offers a kaleidoscope of experiences.',
        '/assets/india.jpg', 1, 14, 8, 24, false, false),
       ('Lübeck', 'City of the Hanseatic League',
        'A medieval city in the North of Germany and home place to the famous Hanseatic League.', '/assets/luebeck.jpg',
        1, 3, 5, 15, false, false),
       ('Canada Rocky Mountains', 'Breathtaking vistas and outdoor adventures.',
        'With stunning alpine lakes and diverse wildlife, it''s a perfect destination for those seeking both adventure and tranquility.',
        '/assets/canada.jpg', 1, 7, 8, 24, false, false),
       ('Japan', 'Rich cultural tapestry, blending tradition with modern innovation.',
        'From serene temples to bustling cityscapes, Japan offers a dynamic tapestry of experiences for travelers to explore.',
        '/assets/japan.jpg', 1, 7, 8, 24, false, false),
       ('Vienna / Wien', 'Dive into the capital of the Habsburg empire',
        'With a population of almost 2 million, Vienna is the second largest German-speaking city and breathes history in every corner.',
        '/assets/vienna.jpg', 1, 3, 5, 12, false, true),
       ('London', 'Explore one of the world''s most famous cities',
        'Being a tourist magnet, this city needs no further introduction.', '/assets/london.jpg', 1, 12, 8, 15, false,
        false),
       ('Detroit', 'Top 10 of the cosmopolitan cities of the world',
        'This US city is mainly known for the autombile industry. It hosts the GM''s headquarters.',
        '/assets/detroit.jpg', 2, 14, 2, 10, false, false),
       ('Reykjavík', 'The northernmost capital of the world and entry to Iceland',
        'Iceland is a small island between Europe and America. It is best known for its nature and landscape which look almost alien.',
        '/assets/reykjavík.jpg', 1, 3, 5, 15, false, false),
       ('Copenhagen / København', 'Europe''s most livable city',
        'Copenhagen is the capital of Denmark and is located on Seenland which is one of the three main Danish islands.',
        '/assets/copenhagen.jpg', 1, 3, 5, 15, true, false),
       ('Shanghai / 上海市', 'East meets West',
        'Although not being the capital of China, Shanghai is a good choice to for a China voyage. It can be reached very easily.',
        '/assets/shanghai.jpg', 1, 3, 5, 15, false, false),
       ('Florence/ Firenze', 'Michelangelo''s David, da Vinci, and Chianti',
        'Birthplace of the Renaissance. Many famous artists left their mark. You can marvel at them at the Uffizi Gallery.',
        '/assets/firenze.jpg', 1, 3, 5, 15, false, false),
       ('Granada', 'Muslim history in Spain',
        'The Alhambra is not just the major attraction in Granada but also counts to the top must-sees in whole Spain.',
        '/assets/granada.jpg', 1, 3, 5, 15, false, false),
       ('Lübeck', 'City of the Hanseatic League',
        'A medieval city in the North of Germany and home place to the famous Hanseatic League.', '/assets/luebeck.jpg',
        1, 3, 5, 15, false, false);